### ISSUE TITLE
ARDebug with showPlanes: true throws an error if a surface is not found quickly.

### ISSUE THREAD

**Issue by nataliawww** [google-ar/three.ar.js#99] opened 2018-02-09 10:57 UTC
##### Description:

Generally finding surfaces is a bit hard, especially on tables / chairs. If I set the debugger's `showPlanes: true`, it throws an error if a plane is not found immediately 

![img_2220](https://user-images.githubusercontent.com/23186467/36024536-50a5dc5a-0d90-11e8-8361-8f1b8da5c102.png)

##### Additional Information:

* three.ar.js version:  latest
* three.js version: 89

- [X ] WebARonARKit (iOS)

**Comment by lincolnfrog** [comment] 2018-02-09 17:14
The surface you are showing should work - try moving your device forward/backwards or in a circle/figure eight pattern.

As far as the error, that looks like a bug. We will investigate. Thanks!

**Comment by jsantell** [comment] 2018-02-11 19:17
Looks like a duplicate of https://github.com/google-ar/WebARonARKit/issues/52

**Closed as completed by jsantell** 2018-02-11 19:17 UTC
